version: '3.6'

services: 
  # backend API
  else-where-project-api: 
    container_name: backend
    build: ./
    command: npm start
    working_dir:  /user/src/ElseWhereProjectApi-v2
    environment: 
      POSTGRES_URI: postgres://sally:secret@postgres:5432/else-where-docker
      REDIS_URI: redis://redis:6379
    ports: 
      - "3000:3000"
    volumes: 
      - ./:/user/src/ElseWhereProjectApi-v2


    
  # postgres
  postgres:
    environment: 
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: else-where-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:        
      - "5432:5432"
  
  # redis 
  redis: 
    image: redis
    ports: 
      - "6379:6379"